on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test-and-deploy:
    concurrency: deploy-group
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      BUILD_AUTHENTICATION_KEY: ${{ secrets.BUILD_AUTHENTICATION_KEY }}
      PORT: 5000

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          node-version: '19.9.0'
      
      - name: Install backend deps
        run: npm install

      - name: Install frontend deps
        run: npm run install:frontend

      - name: Build application for testing
        run: npm run build

      - name: Run jest for both backend and frontend
        run: npm run test:jest
      
      - name: Run e2e tests
        run: npm run test:cypress

      - name: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}


      # The success/fail message scripts send an http request to build api.
      # The commit sha, status and github username are displayed on front
      # page of the application

    
      - name: success message
        run: npm run actions:success

        env:
          commitId: ${{ github.event.pull_request.merge_commit_sha }}
          githubUsername: ${{ github.actor }}

        if: ${{ success() }}

      - name: failure message
        run: npm run actions:fail

        env:
          commitId: ${{ github.event.pull_request.merge_commit_sha }}
          githubUsername: ${{ github.actor }}

        if: ${{ failure() }}

  update-version:
    needs: [test-and-deploy]
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: update version ON MERGE
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

        if: github.event_name == 'push'